# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
# For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  workflow_dispatch:
  pull_request_target:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create dynamic labeler configuration
        env:
          yamlfile: .github/labeler.yml
        run: |
          # Function to find folders, convert to JSON, and append labels to YAML file
          process_folders() {
            local path=$1

            find "$path" -mindepth 1 -maxdepth 1 -type d | grep -v '/\.' | awk -F'/' '{print $NF}' | jq -R -s -c 'split("\n")[:-1]' > folders.json
            echo "$path Folders:"
            cat "$json_file"

            jq -r '.[]' folders.json | while read -r folder; do
              label="${folder//\//-}"
              if [ "${#label}" -gt 63 ]; then
                echo "Label is longer than 63 characters: $label"
                label="${label:0:63}"
                echo "Trimmed label to 63 characters: $label"
              fi
              echo "- $folder -> $label"
              cat >> "${{ env.yamlfile }}" <<EOF
            $label:
              - changed-files:
                - any-glob-to-any-file: '$path/$folder/**'
            EOF
              done
          }

          # Ensure the YAML file exists
          touch "${{ env.yamlfile }}"
          echo "Add dynamic integration labels to ${{ env.yamlfile }}"

          # Process root, project_2, and project_3 folders
          process_folders "."
          process_folders "project_2"
          process_folders "project_3"

          # Display the final output file
          echo "Output file:"
          cat "${{ env.yamlfile }}"

      - name: Apply labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
          config-path: .github/labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
