# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
# For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request_target]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create dynamic labeler configuration
        env:
          yamlfile: .github/labeler.yml
        run: |
          # Ensure the YAML file exists
          touch "${{ env.yamlfile }}"
          echo "Add dynamic integration labels to ${{ env.yamlfile }}"

          for PROJECT in */ project_2/*/ project_3/*/; do
            LABEL="${PROJECT%/}"
            LABEL="${LABEL//\//-}"
            if [ "${#LABEL}" -gt 63 ]; then
              echo "Label is longer than 63 characters: $LABEL"
              LABEL="${LABEL:0:63}"
              echo "Trimmed label to 63 characters: $LABEL"
            fi
            echo "'$LABEL': [{'changed-files': [{ 'any-glob-to-any-file': '$PROJECT**' }]}]" >> "${{ env.yamlfile }}" 
          done

          # Display the final output file
          echo "Output file:"
          cat "${{ env.yamlfile }}"
      - name: Apply labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
          config-path: .github/labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
